
services:

  app:
    build:
      context: node
    container_name: app
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - tmpdb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge

volumes:
  tmpdb:
